# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Copyright 2026, Yuanzhu Li
# Copyright 2026, BAAI (Beijing Academy of Artificial Intelligence)
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(is_tensor=[True, True], promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def beam_search_score_kernel(log_probs, beam_scores):
    # Beam Search Score: Add cumulative log probability with new token log probability
    # This is the core operation in beam search: new_score = old_score + log_prob(token)
    return log_probs + beam_scores


def beam_search_score(log_probs, beam_scores):
    """Compute Beam Search scores by adding cumulative scores with log probabilities.

    In Beam Search, each candidate's score is computed by adding the cumulative
    log probability with the log probability of the new token.

    Args:
        log_probs: Log probabilities for new tokens, shape [batch_size, vocab_size]
        beam_scores: Cumulative beam scores, shape [batch_size] or [batch_size, 1]

    Returns:
        Updated beam scores with shape [batch_size, vocab_size]
    """
    logger.debug("GEMS BEAM_SEARCH_SCORE")

    # Handle broadcasting: beam_scores needs to be broadcast to match log_probs
    log_probs_ndim = log_probs.dim()
    beam_scores_ndim = beam_scores.dim()

    # If beam_scores has fewer dimensions, we need to expand it
    if beam_scores_ndim < log_probs_ndim:
        # Get the broadcast shape
        # beam_scores shape should be [batch_size] and we need to add a dimension
        # at the end for broadcasting with [batch_size, vocab_size]
        if beam_scores_ndim == 1:
            # [batch_size] -> [batch_size, 1]
            beam_scores = beam_scores.unsqueeze(-1)

    if torch.is_tensor(log_probs) and log_probs.device.type == "cpu":
        return log_probs + beam_scores

    return beam_search_score_kernel(log_probs, beam_scores)


def beam_search_score_(log_probs, beam_scores):
    """In-place version of beam_search_score.

    Computes Beam Search scores in-place, modifying log_probs directly.
    """
    logger.debug("GEMS BEAM_SEARCH_SCORE_")

    log_probs_ndim = log_probs.dim()
    beam_scores_ndim = beam_scores.dim()

    if beam_scores_ndim < log_probs_ndim:
        if beam_scores_ndim == 1:
            beam_scores = beam_scores.unsqueeze(-1)

    if torch.is_tensor(log_probs) and log_probs.device.type == "cpu":
        log_probs.copy_(log_probs + beam_scores)
        return log_probs

    return beam_search_score_kernel(log_probs, beam_scores, out0=log_probs)
