# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
from typing import List

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def _chunk_cat_kernel_1d(
    input_ptr,
    output_ptr,
    input_size,
    chunk_size,
    total_output_elements,
    BLOCK_SIZE: tl.constexpr,
):
    """Kernel for 1D input tensor."""
    pid = tl.program_id(0)
    block_start = pid * BLOCK_SIZE
    offsets = tl.arange(0, BLOCK_SIZE)
    mask = block_start + offsets < total_output_elements

    out_idx = block_start + offsets
    chunk_idx = out_idx // chunk_size
    within_chunk = out_idx % chunk_size
    orig_idx = chunk_idx * chunk_size + within_chunk
    data = tl.load(input_ptr + orig_idx, mask=mask & (orig_idx < input_size))
    tl.store(output_ptr + out_idx, data, mask=mask)


@triton.jit
def _chunk_cat_kernel_2d_dim0(
    input_ptr,
    output_ptr,
    input_size_0,
    input_size_1,
    chunk_size,
    total_output_elements,
    BLOCK_SIZE: tl.constexpr,
):
    """Kernel for 2D input tensor with dim=0."""
    pid = tl.program_id(0)
    block_start = pid * BLOCK_SIZE
    offsets = tl.arange(0, BLOCK_SIZE)
    mask = block_start + offsets < total_output_elements

    out_idx = block_start + offsets
    remaining = input_size_1

    chunk_idx = out_idx // (chunk_size * remaining)
    remainder = out_idx % (chunk_size * remaining)

    row_offset = remainder // remaining
    col = remainder % remaining

    orig_row = chunk_idx * chunk_size + row_offset
    orig_idx = orig_row * remaining + col
    valid = mask & (orig_row < input_size_0)

    data = tl.load(input_ptr + orig_idx, mask=valid)
    tl.store(output_ptr + out_idx, data, mask=mask)


@triton.jit
def _chunk_cat_kernel_2d_dim1(
    input_ptr,
    output_ptr,
    input_size_0,
    input_size_1,
    num_chunks,
    chunk_size,
    total_output_elements,
    BLOCK_SIZE: tl.constexpr,
):
    """Kernel for 2D input tensor with dim=1."""
    pid = tl.program_id(0)
    block_start = pid * BLOCK_SIZE
    offsets = tl.arange(0, BLOCK_SIZE)
    mask = block_start + offsets < total_output_elements

    out_idx = block_start + offsets

    row = out_idx // (num_chunks * chunk_size)
    remainder = out_idx % (num_chunks * chunk_size)
    chunk_idx = remainder // chunk_size
    within_chunk = remainder % chunk_size

    orig_col = chunk_idx * chunk_size + within_chunk
    orig_idx = row * input_size_1 + orig_col
    valid = mask & (orig_col < input_size_1)

    data = tl.load(input_ptr + orig_idx, mask=valid)
    tl.store(output_ptr + out_idx, data, mask=mask)


@triton.jit
def _chunk_cat_kernel_nd(
    input_ptr,
    output_ptr,
    dim_size,
    num_chunks,
    chunk_size,
    stride_before,
    stride_after,
    total_output_elements,
    BLOCK_SIZE: tl.constexpr,
):
    """Generic kernel for N-D input tensor along any dim."""
    pid = tl.program_id(0)
    block_start = pid * BLOCK_SIZE
    offsets = tl.arange(0, BLOCK_SIZE)
    out_idx = block_start + offsets
    mask = out_idx < total_output_elements

    # Output layout: [...before..., num_chunks, chunk_size, ...after...]
    chunk_block = chunk_size * stride_after
    full_block = num_chunks * chunk_block

    before_idx = out_idx // full_block
    remainder = out_idx % full_block
    chunk_idx = remainder // chunk_block
    remainder2 = remainder % chunk_block
    within = remainder2 // stride_after
    after_idx = remainder2 % stride_after

    orig_dim_idx = chunk_idx * chunk_size + within
    orig_idx = (
        before_idx * (dim_size * stride_after) + orig_dim_idx * stride_after + after_idx
    )
    valid = mask & (orig_dim_idx < dim_size)

    data = tl.load(input_ptr + orig_idx, mask=valid, other=0.0)
    tl.store(output_ptr + out_idx, data, mask=mask)


def _chunk_cat_triton_1d(
    tensor: torch.Tensor, dim: int, num_chunks: int
) -> torch.Tensor:
    """Handle 1D tensor case."""
    input_size = tensor.shape[0]
    chunk_size = (input_size + num_chunks - 1) // num_chunks

    output_shape = [num_chunks, chunk_size]
    output = torch.empty(output_shape, dtype=tensor.dtype, device=tensor.device)

    # Block size for 1D kernel: 1024 elements per thread block for good GPU occupancy
    BLOCK = 1024
    total_output = num_chunks * chunk_size
    grid = (triton.cdiv(total_output, BLOCK),)

    _chunk_cat_kernel_1d[grid](
        tensor,
        output,
        input_size,
        chunk_size,
        total_output,
        BLOCK_SIZE=BLOCK,
    )

    return output


def _chunk_cat_triton_2d(
    tensor: torch.Tensor, dim: int, num_chunks: int
) -> torch.Tensor:
    """Handle 2D tensor case."""
    input_size_0, input_size_1 = tensor.shape
    chunk_size = (
        (input_size_0 + num_chunks - 1) // num_chunks
        if dim == 0
        else (input_size_1 + num_chunks - 1) // num_chunks
    )

    if dim == 0:
        remaining = input_size_1
        output_shape = [num_chunks, chunk_size * remaining]
    else:
        output_shape = [input_size_0, num_chunks, chunk_size]

    output = torch.empty(output_shape, dtype=tensor.dtype, device=tensor.device)

    # Block size for 2D kernel: 1024 elements per thread block for good GPU occupancy
    BLOCK = 1024
    total_output = 1
    for s in output_shape:
        total_output *= s
    grid = (triton.cdiv(total_output, BLOCK),)

    if dim == 0:
        _chunk_cat_kernel_2d_dim0[grid](
            tensor,
            output,
            input_size_0,
            input_size_1,
            chunk_size,
            total_output,
            BLOCK_SIZE=BLOCK,
        )
    else:
        _chunk_cat_kernel_2d_dim1[grid](
            tensor,
            output,
            input_size_0,
            input_size_1,
            num_chunks,
            chunk_size,
            total_output,
            BLOCK_SIZE=BLOCK,
        )

    return output


def _chunk_cat_triton_nd(
    tensor: torch.Tensor, dim: int, num_chunks: int
) -> torch.Tensor:
    """Handle N-D tensor case using generic kernel."""
    dim_size = tensor.shape[dim]
    chunk_size = (dim_size + num_chunks - 1) // num_chunks

    stride_before = 1
    for i in range(dim):
        stride_before *= tensor.shape[i]

    stride_after = 1
    for i in range(dim + 1, tensor.ndim):
        stride_after *= tensor.shape[i]

    output_shape = (
        list(tensor.shape[:dim])
        + [num_chunks, chunk_size]
        + list(tensor.shape[dim + 1 :])
    )
    output = torch.empty(output_shape, dtype=tensor.dtype, device=tensor.device)

    BLOCK = 1024
    total_output = stride_before * num_chunks * chunk_size * stride_after
    grid = (triton.cdiv(total_output, BLOCK),)

    _chunk_cat_kernel_nd[grid](
        tensor,
        output,
        dim_size,
        num_chunks,
        chunk_size,
        stride_before,
        stride_after,
        total_output,
        BLOCK_SIZE=BLOCK,
    )

    return output


def _chunk_cat_triton(tensor: torch.Tensor, dim: int, num_chunks: int) -> torch.Tensor:
    """Main Triton implementation for single tensor."""
    dim = dim % tensor.ndim

    if tensor.numel() == 0:
        # Return empty tensor with correct output shape
        dim_size = tensor.shape[dim]
        chunk_size = (dim_size + num_chunks - 1) // num_chunks if dim_size > 0 else 0
        output_shape = (
            list(tensor.shape[:dim])
            + [num_chunks, chunk_size]
            + list(tensor.shape[dim + 1 :])
        )
        return torch.empty(output_shape, dtype=tensor.dtype, device=tensor.device)

    if tensor.ndim == 1:
        return _chunk_cat_triton_1d(tensor, dim, num_chunks)
    elif tensor.ndim == 2:
        return _chunk_cat_triton_2d(tensor, dim, num_chunks)
    else:
        return _chunk_cat_triton_nd(tensor, dim, num_chunks)


def _chunk_cat_impl(
    tensors: List[torch.Tensor], dim: int, num_chunks: int
) -> torch.Tensor:
    """Implementation of _chunk_cat with multiple tensor support."""
    if len(tensors) == 0:
        raise ValueError("_chunk_cat(): expected a non-empty list of Tensors")

    if num_chunks <= 0:
        raise ValueError(f"_chunk_cat(): num_chunks must be positive, got {num_chunks}")

    ndim = tensors[0].ndim
    if ndim == 0:
        raise ValueError("_chunk_cat(): expected tensors with at least 1 dimension")
    if dim < -ndim or dim >= ndim:
        raise IndexError(
            f"_chunk_cat(): dim {dim} out of range for tensor with {ndim} dimensions"
        )

    if len(tensors) == 1:
        return _chunk_cat_triton(tensors[0], dim, num_chunks)

    # Multiple tensors case
    # NOTE: The multi-tensor path uses PyTorch ops (chunk, cat, stack) rather than a
    # custom Triton kernel. A fused Triton kernel for multi-tensor _chunk_cat is left
    # as a future optimization.
    dim = dim % ndim
    dim_size = tensors[0].shape[dim]
    chunk_size = (dim_size + num_chunks - 1) // num_chunks
    device = tensors[0].device
    dtype = tensors[0].dtype
    num_tensors = len(tensors)

    # For multiple tensors, we:
    # 1. Chunk each tensor into num_chunks pieces (padding as needed)
    # 2. Concatenate corresponding chunks from each tensor

    # First chunk each tensor
    all_chunked = []
    for tensor in tensors:
        chunks = torch.chunk(tensor, num_chunks, dim=dim)

        # Pad each chunk to chunk_size
        padded_chunks = []
        for chunk in chunks:
            pad_shape = list(chunk.shape)
            pad_shape[dim] = chunk_size - chunk.shape[dim]
            if pad_shape[dim] > 0:
                padding_tensor = torch.zeros(pad_shape, dtype=dtype, device=device)
                chunk = torch.cat([chunk, padding_tensor], dim=dim)
            padded_chunks.append(chunk)

        # Stack to get [num_chunks, ...] shape
        chunked = torch.stack(padded_chunks, dim=dim)
        all_chunked.append(chunked)

    # Now interleave: for each chunk index, concatenate tensors' chunks
    # Result shape: [..., num_chunks, chunk_size * num_tensors, ...] (for dim > 0)
    # For dim=0: [num_chunks, chunk_size * num_tensors * remaining]

    if dim == 0:
        # For dim=0: output shape is [num_chunks, chunk_size * num_tensors * remaining]
        if ndim == 1:
            remaining = 1
        else:
            remaining = 1
            for i in range(1, ndim):
                remaining *= tensors[0].shape[i]
        output_shape = [num_chunks, chunk_size * num_tensors * remaining]

        # Build output
        output = torch.zeros(output_shape, dtype=dtype, device=device)

        for chunk_idx in range(num_chunks):
            for tensor_idx, chunk_data in enumerate(
                [all_chunked[t][chunk_idx] for t in range(num_tensors)]
            ):
                # chunk_data has shape [chunk_size, ...] (remaining dims)
                src_flat = chunk_data.flatten()
                dst_start = chunk_idx * (
                    chunk_size * num_tensors * remaining
                ) + tensor_idx * (chunk_size * remaining)
                dst_flat = output.view(-1)
                dst_flat[dst_start : dst_start + len(src_flat)] = src_flat
    else:
        # For dim > 0: output shape inserts num_chunks at position dim, chunk_size * num_tensors at dim+1
        output_shape = list(tensors[0].shape)
        # Replace dimension dim with num_chunks, insert chunk_size * num_tensors at dim+1
        new_shape = []
        for i in range(ndim):
            if i < dim:
                new_shape.append(tensors[0].shape[i])
            elif i == dim:
                new_shape.append(num_chunks)
            elif i == dim + 1:
                new_shape.append(chunk_size * num_tensors)
            else:
                new_shape.append(tensors[0].shape[i])
        output_shape = new_shape

        output = torch.zeros(output_shape, dtype=dtype, device=device)

        # Build output by iterating over chunks
        for chunk_idx in range(num_chunks):
            for tensor_idx in range(num_tensors):
                chunk_data = all_chunked[tensor_idx][chunk_idx]

                # Create index for output
                output_idx = [slice(None)] * ndim
                output_idx[dim] = chunk_idx
                output_idx[dim + 1] = slice(
                    tensor_idx * chunk_size, (tensor_idx + 1) * chunk_size
                )

                output[tuple(output_idx)] = chunk_data

    return output


def chunk_cat(tensors: List[torch.Tensor], dim: int, num_chunks: int) -> torch.Tensor:
    """_chunk_cat operator."""
    logger.debug("GEMS _chunk_cat")
    return _chunk_cat_impl(tensors, dim, num_chunks)
