# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

logger = logging.getLogger(__name__)


def _unsafe_view(self: torch.Tensor, size):
    """Reshape the tensor to the given size without safety checks.

    Uses PyTorch's reshape which returns a view for contiguous tensors
    and a copy for non-contiguous tensors.
    """
    logger.debug("GEMS UNSAFE_VIEW")
    return self.reshape(size)
