# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import importlib
import logging
import os
from typing import Any, Callable, Mapping, Tuple

import torch

from flag_gems.utils.code_cache import code_cache_dir
from flag_gems.utils.code_utils import IndentedBuffer, write_atomic

logger = logging.getLogger(__name__)


def generate_imports(code: IndentedBuffer) -> IndentedBuffer:
    code.writeline("import triton")
    code.writeline("import triton.language as tl")
    code.newline()
    code.writeline("from flag_gems.utils import libentry")
    code.writeline("from flag_gems.utils import triton_lang_extension as tle")
    code.newline()
    code.newline()
    return code


def generate_kernel(rank, kernel_name: str, code: IndentedBuffer):
    code.writeline("@libentry()")
    code.writeline("@triton.jit")
    code.writeline(f"def {kernel_name}(")
    with code.indent():
        code.writeline("input_ptr,")
        code.writeline("mask_ptr,")
        code.writeline("indices_ptr,")
        code.writeline("values_ptr,")
        code.writeline("mask_numel,")
        code.writeline("input_numel,")
        for i in range(rank):
            code.writeline(f"input_shape{i},")
        for i in range(rank):
            code.writeline(f"input_stride{i},")
        code.writeline(
            "BLOCK_SIZE: tl.constexpr = 2048,  # Power-of-2 block size for GPU occupancy"
        )
    code.writeline("):")
    with code.indent():
        code.writeline("pid = tl.program_id(axis=0)")
        code.writeline("offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)")
        code.writeline("mask_mask = offsets < mask_numel")
        code.newline()
        code.writeline("# Load mask, indices, values at flat offset")
        code.writeline(
            "mask_val = tl.load(mask_ptr + offsets, mask=mask_mask, other=0)"
        )
        code.newline()
        code.writeline(
            "indices_val = tl.load(indices_ptr + offsets, mask=mask_mask, other=0).to(tl.int32)"
        )
        code.newline()
        code.writeline(
            "values_val = tl.load(values_ptr + offsets, mask=mask_mask, other=0)"
        )
        code.newline()
        # Convert linear index from indices tensor to multi-dimensional index in input
        code.writeline("# Convert linear index to multi-dimensional offset in input")
        # First compute the multi-dimensional index in input
        code.writeline("temp_idx = indices_val")
        for i in range(rank - 1, -1, -1):
            if i == 0:
                code.writeline(f"input_idx{i} = temp_idx")
            else:
                code.writeline(f"input_idx{i} = temp_idx % input_shape{i}")
                code.writeline(f"temp_idx = temp_idx // input_shape{i}")
        code.newline()
        # Then compute the memory offset
        code.writeline("# Compute memory offset in input tensor")
        comp = [f"input_idx{i} * input_stride{i}" for i in range(rank)]
        code.writeline(f"dest_offset = {' + '.join(comp)}")
        code.newline()
        code.writeline("# Validate index is within bounds")
        code.writeline("index_valid = (indices_val >= 0) & (indices_val < input_numel)")
        code.writeline("final_mask = mask_mask & (mask_val != 0) & index_valid")
        code.newline()
        code.writeline(
            "# Atomic add at destination, only where mask is True and index is valid"
        )
        code.writeline(
            "tl.atomic_add(input_ptr + dest_offset, values_val, mask=final_mask, sem='relaxed')"
        )
    code.newline()
    code.newline()
    return code


def generate_wrapper(rank, wrapper_name: str, kernel_name: str, code: IndentedBuffer):
    code.writeline(f"def {wrapper_name}(input, mask, indices, values):")
    with code.indent():
        code.writeline("input_numel = input.numel()")
        code.writeline("mask_numel = mask.numel()")
        code.newline()
        code.writeline("# Get input shape and strides")
        for i in range(rank):
            code.writeline(f"input_shape{i} = input.shape[{i}]")
        for i in range(rank):
            code.writeline(f"input_stride{i} = input.stride()[{i}]")
        code.newline()
        code.writeline("BLOCK_SIZE = 2048  # Power-of-2 block size for GPU occupancy")
        code.writeline("grid = (triton.cdiv(mask_numel, BLOCK_SIZE),)")
        code.newline()
        code.writeline(f"{kernel_name}[grid](")
        with code.indent():
            code.writeline("input,")
            code.writeline("mask,")
            code.writeline("indices,")
            code.writeline("values,")
            code.writeline("mask_numel,")
            code.writeline("input_numel,")
            for i in range(rank):
                code.writeline(f"input_shape{i},")
            for i in range(rank):
                code.writeline(f"input_stride{i},")
            code.writeline("BLOCK_SIZE=BLOCK_SIZE")
        code.writeline(")")
        code.writeline("return input")
    code.newline()
    code.newline()
    return code


def generate_code(
    inputs: Tuple[Any],
    wrapper_name: str,
    kernel_name: str,
    code: IndentedBuffer,
):
    input_tensor = inputs[0]
    rank = input_tensor.ndim
    code = generate_imports(code)
    generate_kernel(rank, kernel_name, code)
    generate_wrapper(rank, wrapper_name, kernel_name, code)
    return code


class UnsafeMaskedIndexPutAccumulateFunction:
    def __init__(self):
        self.pid = os.getpid()
        self.overloads: Mapping[str, Callable] = {}

    def __call__(self, *args, **kwargs):
        key = self.arg_key(*args)
        if key in self.overloads:
            overload = self.overloads[key]
        else:
            code = IndentedBuffer()
            code = generate_code(
                args,
                "_unsafe_masked_index_put_accumulate_wrapper",
                "_unsafe_masked_index_put_accumulate_jit",
                code,
            )
            file_name = f"unsafe_masked_index_put_accumulate_{key}_pid_{self.pid}.py"
            file_path = code_cache_dir() / file_name
            write_atomic(file_path, code.getvalue())

            spec = importlib.util.spec_from_file_location(
                f"_gen_module_{key}_pid_{self.pid}",
                file_path,
            )

            m = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(m)
            overload = getattr(m, "_unsafe_masked_index_put_accumulate_wrapper")
            self.overloads[key] = overload

        return overload(*args)

    def arg_key(self, *args):
        input_tensor, mask, indices, values = args
        return f"rank_{input_tensor.ndim}"


def _unsafe_masked_index_put_accumulate(inp, mask, indices, values):
    logger.debug("GEMS UNSAFE_MASKED_INDEX_PUT_ACCUMULATE")
    unsafe_masked_index_put_accumulate_func = UnsafeMaskedIndexPutAccumulateFunction()

    # indices is Tensor?[] - a list/tuple of optional tensors (torch convention).
    # Each element indexes one dimension. The kernel expects a single flat
    # (linear) index tensor, so convert per-dimension indices when needed.
    if isinstance(indices, (list, tuple)):
        if len(indices) == 0 or indices[0] is None:
            raise ValueError("Empty indices list")
        if len(indices) == 1:
            indices_tensor = indices[0]
        else:
            # Per-dimension -> flat linear: idx0*stride0 + idx1*stride1 + ...
            # Row-major: stride[i] = product of shapes[i+1 .. rank-1]
            rank = inp.ndim
            indices_tensor = indices[0].to(torch.int32).clone()
            stride = 1
            for j in range(1, rank):
                stride *= inp.shape[j]
            indices_tensor *= stride
            for dim in range(1, rank):
                stride = 1
                for j in range(dim + 1, rank):
                    stride *= inp.shape[j]
                indices_tensor += indices[dim].to(torch.int32) * stride
    else:
        indices_tensor = indices

    # Validate shapes
    assert mask.shape == indices_tensor.shape, (
        f"mask and indices must have same shape, got {mask.shape} "
        f"and {indices_tensor.shape}"
    )
    assert mask.shape == values.shape, (
        f"mask and values must have same shape, got {mask.shape} " f"and {values.shape}"
    )

    # Ensure same device
    inp = inp.to(values.device) if inp.device != values.device else inp.clone()
    mask = mask.to(inp.device) if mask.device != inp.device else mask
    indices_tensor = (
        indices_tensor.to(inp.device)
        if indices_tensor.device != inp.device
        else indices_tensor
    )
    values = values.to(inp.device) if values.device != inp.device else values

    return unsafe_masked_index_put_accumulate_func(inp, mask, indices_tensor, values)
