# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, "INT_TO_FLOAT")])
@triton.jit
def acosh_func(x):
    # acosh(x) = log(x + sqrt(x*x - 1))
    # Domain: [1, inf), returns NaN for x < 1 (except x=1 returns 0)
    x_f32 = x.to(tl.float32)
    # For x < 1, the result should be NaN
    # We need to handle x >= 1 case
    # Using the formula: acosh(x) = log(x + sqrt(x*x - 1))
    sqrt_term = tl.sqrt(x_f32 * x_f32 - 1.0)
    result = tl.log(x_f32 + sqrt_term)
    return result.to(x.dtype)


def acosh(A):
    logger.debug("GEMS ACOSH")
    return acosh_func(A)


def acosh_(A):
    logger.debug("GEMS ACOSH_")
    acosh_func(A, out0=A)
    return A
