# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl  # noqa: F401

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(is_tensor=[True], promotion_methods=[(0, "DEFAULT")])
@triton.jit
def copy_func(x):
    return x


def diagonal_scatter(input, src, offset=0, dim1=0, dim2=1):
    """Scatter src values into the diagonal of a clone of input.

    Args:
        input: Input tensor (at least 2-D).
        src: Source tensor whose shape matches the diagonal.
        offset: Diagonal offset. 0 for main diagonal, positive for upper,
                negative for lower.
        dim1: First dimension for the 2-D sub-tensor.
        dim2: Second dimension for the 2-D sub-tensor.

    Returns:
        A new tensor with src values scattered along the specified diagonal.
    """
    logger.debug("GEMS DIAGONAL_SCATTER")
    output = input.clone()
    diag = torch.diagonal(output, offset, dim1, dim2)
    copy_func.instantiate(src.ndim)(src, out0=diag)
    return output
