# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic
from flag_gems.utils.triton_lang_extension import trunc

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, "DEFAULT")])
@triton.jit
def frac_func(x):
    # frac(x) = x - trunc(x), where trunc(x) is truncation toward zero
    # Convert to float32 for computation to avoid precision issues with bfloat16
    x_fp32 = x.to(tl.float32)
    return (x_fp32 - trunc(x_fp32)).to(x.dtype)


def frac(A):
    logger.debug("GEMS FRAC")
    return frac_func(A)


def frac_(A):
    logger.debug("GEMS FRAC_")
    frac_func(A, out0=A)
    return A
