# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
"""greater_equal is an alias for ge (greater-or-equal). The Tensor and Scalar
overloads reuse the existing ge.py implementation directly via alias registration
in flag_gems/__init__.py. This file only provides the inplace wrapper
greater_equal_ since ge.py does not have an inplace variant."""
import logging

from flag_gems.ops.ge import ge_func

logger = logging.getLogger(__name__)


def greater_equal_(A, B):
    logger.debug("GEMS GREATER_EQUAL_")
    if A.device != B.device:
        B = B.to(A.device)
    return ge_func(A, B, out0=A)
