# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems import runtime
from flag_gems.utils import dim_compress, libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.autotune(
    configs=runtime.get_tuned_config("index_select_backward"),
    key=["index_len"],
    restore_value=["out_ptr"],
)
@triton.jit
def index_select_backward_kernel(
    out_ptr,
    grad_ptr,
    index_ptr,
    feat_size,
    index_len,
    dim_size_out,
    BLOCK: tl.constexpr,
):
    fid = tl.program_id(0)
    pid = tl.program_id(1)

    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < index_len

    idx = tl.load(index_ptr + offs, mask=mask, other=0)
    grad_offs = fid * index_len + offs
    g = tl.load(grad_ptr + grad_offs, mask=mask, other=0.0)

    out_offs = fid * dim_size_out + idx
    tl.atomic_add(out_ptr + out_offs, g, mask=mask)


def index_select_backward(grad, self_sizes, dim, index):
    """
    Backward of index_select.

    `grad` is the gradient w.r.t. the output of index_select, of the same shape
    as `self_sizes` except that the `dim` axis has length `index.numel()`.
    Accumulates each slice of `grad` along `dim` into a zero tensor of shape
    `self_sizes` at the offset given by `index`, i.e.

        out[..., index[i], ...] += grad[..., i, ...]   (along `dim`)

    Returns the gradient w.r.t. the original `self`, of shape `self_sizes`.
    """
    logger.debug("GEMS INDEX_SELECT_BACKWARD")

    if index.ndim == 0:
        index = index.unsqueeze(0)

    index = index.to(torch.int64)
    index_len = index.numel()

    dim = dim if dim >= 0 else dim + len(self_sizes)
    dim_size_out = self_sizes[dim]

    orig_dtype = grad.dtype
    if grad.dtype in (torch.float16, torch.bfloat16):
        grad = grad.to(torch.float32)

    out = torch.zeros(self_sizes, dtype=grad.dtype, device=grad.device)

    # Move the target dim to the last position via dim_compress
    grad_compressed = dim_compress(grad, dim)
    out_compressed = dim_compress(out, dim)

    compressed_shape = list(out_compressed.shape)

    # Flatten all non-last dimensions into feat_size
    grad_flat = grad_compressed.reshape(-1, index_len)
    out_flat = out_compressed.reshape(-1, dim_size_out)

    feat_size = grad_flat.shape[0]

    grid = lambda meta: (
        feat_size,
        triton.cdiv(index_len, meta["BLOCK"]),
    )

    index_select_backward_kernel[grid](
        out_flat,
        grad_flat,
        index,
        feat_size,
        index_len,
        dim_size_out,
    )

    # Reshape to compressed shape, then permute back to original dim order
    out_flat = out_flat.reshape(compressed_shape)

    if dim != grad.ndim - 1:
        ndim_compressed = out_flat.ndim
        order = [i for i in range(ndim_compressed - 1)]
        order.insert(dim, ndim_compressed - 1)
        out = out_flat.permute(order).contiguous()
    else:
        out = out_flat

    if orig_dtype in (torch.float16, torch.bfloat16):
        return out.to(orig_dtype)
    return out
