# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl  # noqa: F401

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, "ALWAYS_BOOL")])
@triton.jit
def is_nonzero_func(x):
    return x != 0


def is_nonzero(A: torch.Tensor) -> bool:
    """Returns True if the input is a single element tensor which is not equal to zero.

    Args:
        A: Input tensor, must have exactly one element.

    Returns:
        bool: True if the element is non-zero, False otherwise.
    """
    logger.debug("GEMS ISNONZERO")
    if A.numel() != 1:
        raise RuntimeError("bool value of Tensor with more than one value is ambiguous")
    result = is_nonzero_func(A)
    return result.item()
