# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems import runtime
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.autotune(
    configs=runtime.get_tuned_config("max_unpool2d"),
    key=["out_h", "out_w", "pooled_h", "pooled_w"],
)
@triton.jit
def max_unpool2d_kernel(
    pooled_ptr,
    indices_ptr,
    output_ptr,
    # Input tensor strides (pooled)
    pooled_stride_n,
    pooled_stride_c,
    pooled_stride_h,
    pooled_stride_w,
    # Output tensor strides
    out_stride_n,
    out_stride_c,
    out_stride_h,
    out_stride_w,
    # Shapes
    n,
    c,
    pooled_h,
    pooled_w,
    out_h,
    out_w,
    # Tiling parameters
    BLOCK_H: tl.constexpr,
    BLOCK_W: tl.constexpr,
):
    pid_nc = tl.program_id(0)
    pid_hw = tl.program_id(1)

    num_w_blocks = tl.cdiv(pooled_w, BLOCK_W)
    h_block_idx = pid_hw // num_w_blocks
    w_block_idx = pid_hw % num_w_blocks
    n_idx = pid_nc // c
    c_idx = pid_nc % c

    h_offsets = h_block_idx * BLOCK_H + tl.arange(0, BLOCK_H)
    w_offsets = w_block_idx * BLOCK_W + tl.arange(0, BLOCK_W)

    pooled_base_ptr = pooled_ptr + n_idx * pooled_stride_n + c_idx * pooled_stride_c
    indices_base_ptr = indices_ptr + n_idx * pooled_stride_n + c_idx * pooled_stride_c

    output_base_ptr = output_ptr + n_idx * out_stride_n + c_idx * out_stride_c

    # Load pooled values and indices
    pooled_offsets = (
        h_offsets[:, None] * pooled_stride_h + w_offsets[None, :] * pooled_stride_w
    )
    indices_offsets = (
        h_offsets[:, None] * pooled_stride_h + w_offsets[None, :] * pooled_stride_w
    )

    pooled_mask = (h_offsets[:, None] < pooled_h) & (w_offsets[None, :] < pooled_w)
    indices_mask = pooled_mask

    pooled_vals = tl.load(pooled_base_ptr + pooled_offsets, mask=pooled_mask, other=0.0)
    indices_flat = tl.load(
        indices_base_ptr + indices_offsets, mask=indices_mask, other=0
    )

    # Convert flat indices to 2D positions in output
    h_orig = indices_flat // out_w
    w_orig = indices_flat % out_w

    # Compute output offsets
    out_offsets = h_orig * out_stride_h + w_orig * out_stride_w

    # Store values at original positions
    # Bounds check: flat indices decoded from max_pool2d may land outside
    # the output tensor when input dims are not evenly divisible by stride
    # (e.g. ceil_mode=False MaxPool on odd-sized dims). In that case skip.
    in_bounds = (h_orig >= 0) & (h_orig < out_h) & (w_orig >= 0) & (w_orig < out_w)
    out_mask = (
        (h_offsets[:, None] < pooled_h) & (w_offsets[None, :] < pooled_w) & in_bounds
    )
    tl.store(output_base_ptr + out_offsets, pooled_vals, mask=out_mask)


def max_unpool2d(pooled: torch.Tensor, indices: torch.Tensor, output_size: list):
    logger.debug("GEMS MAX_UNPOOL2D")

    pooled = pooled.contiguous()
    indices = indices.contiguous()

    n, c, pooled_h, pooled_w = pooled.shape
    out_h, out_w = output_size[0], output_size[1]

    output = torch.zeros((n, c, out_h, out_w), device=pooled.device, dtype=pooled.dtype)

    if output.numel() == 0:
        return output

    grid = lambda meta: (
        n * c,
        triton.cdiv(pooled_h, meta["BLOCK_H"]) * triton.cdiv(pooled_w, meta["BLOCK_W"]),
    )

    max_unpool2d_kernel[grid](
        pooled,
        indices,
        output,
        pooled.stride(0),
        pooled.stride(1),
        pooled.stride(2),
        pooled.stride(3),
        output.stride(0),
        output.stride(1),
        output.stride(2),
        output.stride(3),
        n,
        c,
        pooled_h,
        pooled_w,
        out_h,
        out_w,
    )

    return output
