# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as tle

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def mse_loss_backward_kernel(
    grad_output_ptr,
    self_ptr,
    target_ptr,
    out_ptr,
    N,
    M,
    reduction,
    BLOCK_M: tl.constexpr,
):
    """Kernel for mse_loss_backward.

    grad = 2 * (self - target) * grad_output / factor
    where factor = 1 for reduction=none/sum, N for reduction=mean
    """
    pid = tle.program_id(0)
    offset = pid * BLOCK_M + tl.arange(0, BLOCK_M)
    mask = offset < M

    # Load data (flattened view)
    grad_val = tl.load(grad_output_ptr + offset, mask=mask, other=0.0).to(tl.float32)
    self_val = tl.load(self_ptr + offset, mask=mask, other=0.0).to(tl.float32)
    target_val = tl.load(target_ptr + offset, mask=mask, other=0.0).to(tl.float32)

    diff = self_val - target_val

    # reduction: 0 = none, 1 = mean, 2 = sum
    # factor = N for mean, 1 otherwise
    factor = tl.where(reduction == 1, N, 1.0)
    grad = (2.0 * diff * grad_val) / factor

    tl.store(out_ptr + offset, grad.to(out_ptr.dtype.element_ty), mask=mask)


def mse_loss_backward(grad_output, self, target, reduction=1):
    """Compute the gradient of mse_loss.

    Args:
        grad_output: Upstream gradient
        self: Input tensor (predictions)
        target: Target tensor
        reduction: Reduction mode (0=none, 1=mean, 2=sum)
    """
    logger.debug("GEMS MSE_LOSS_BACKWARD")

    # Save original shape
    original_shape = self.shape

    # Flatten tensors to 1D
    grad_output = grad_output.flatten()
    self = self.flatten()
    target = target.flatten()

    M = self.numel()

    # Allocate output
    out = torch.empty_like(self)

    # Determine block size
    BLOCK_M = min(triton.next_power_of_2(M), 1024)
    grid = (triton.cdiv(M, BLOCK_M),)

    mse_loss_backward_kernel[grid](
        grad_output,
        self,
        target,
        out,
        M,  # N = M for scalar reduction
        M,
        reduction,
        BLOCK_M=BLOCK_M,
    )

    # Reshape output to original shape
    out = out.reshape(original_shape)

    return out
