# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic, tl_extra_shim

logger = logging.getLogger(__name__)


@pointwise_dynamic(is_tensor=[True, True], promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def nextafter_func(input, other):
    # IEEE 754 nextafter: returns the next representable float after input towards other
    # For float16/bfloat16: use bit manipulation on the uint16 representation to
    # compute the next value in the native precision.  Computing in float32 then
    # casting back would silently skip intermediate fp16/bf16 values because the
    # float32 next value may round to the same lower-precision value (e.g.
    # nextafter(1., 2.) in fp16 is 1.0009765625, but the fp32 next value
    # 1.00000012 rounds back to 1.0 in fp16).
    # For float32: use libdevice's nextafter (which also handles NaN / Inf / same).
    dtype = input.dtype
    if tl.constexpr(dtype == tl.float16) or tl.constexpr(dtype == tl.bfloat16):
        # NaN check: all exponent bits set and mantissa non-zero
        if tl.constexpr(dtype == tl.float16):
            exp_mask = 0x7C00  # 5 exponent bits
            frac_mask = 0x03FF  # 10 mantissa bits
        else:  # bf16
            exp_mask = 0x7F80  # 8 exponent bits
            frac_mask = 0x007F  # 7 mantissa bits

        x_int = input.to(tl.uint16, bitcast=True)
        y_int = other.to(tl.uint16, bitcast=True)

        # NaN: all exponent bits set and mantissa non-zero
        x_is_nan = ((x_int & exp_mask) == exp_mask) & ((x_int & frac_mask) != 0)
        y_is_nan = ((y_int & exp_mask) == exp_mask) & ((y_int & frac_mask) != 0)
        is_nan = x_is_nan | y_is_nan

        # Same value: return input (matches IEEE 754)
        is_equal = input == other

        sign_bit = 0x8000
        is_positive = (x_int & sign_bit) == 0
        is_going_up = input < other

        # --- uint16 constants via bitwise ops (arithmetic on uint16 + Python int
        #     would promote to int32, breaking the final bitcast) ---
        uint_zero = x_int & 0  # uint16(0)
        uint_one = uint_zero | 1  # uint16(1)
        uint_neg_one = ~uint_zero  # uint16(0xFFFF) = -1 in uint16 arithmetic
        cross_const = uint_zero | 0x8001  # uint16(0x8001)

        # Manipulate the unsigned integer representation.
        # IEEE 754 sign-magnitude means that for positive numbers a larger
        # uint corresponds to a larger float value, while for negative numbers
        # a larger uint corresponds to a more-negative (smaller) float value.
        #
        # Normal increment:
        #   positive going up:     x_int + 1
        #   positive going down:   x_int - 1  (= x_int + 0xFFFF in uint16)
        #   negative going up:     x_int - 1  (less negative)
        #   negative going down:   x_int + 1  (more negative)
        normal_inc = tl.where(
            is_positive,
            tl.where(is_going_up, uint_one, uint_neg_one),
            tl.where(is_going_up, uint_neg_one, uint_one),
        )

        # Zero-crossing needs special handling:
        #   +0 going down: 0x0000 should become 0x8001 (largest negative subnormal)
        #   -0 going up:   0x8000 should become 0x0001 (smallest positive subnormal)
        # In both cases x_int + 0x8001 gives the correct result in uint16:
        #   0x0000 + 0x8001 = 0x8001  (target)
        #   0x8000 + 0x8001 = 0x0001  (wraps around in uint16)
        pos_zero_down = is_positive & ~is_going_up & (x_int == 0)
        neg_zero_up = ~is_positive & is_going_up & (x_int == 0x8000)
        is_zero_cross = pos_zero_down | neg_zero_up

        result_int = tl.where(
            is_nan | is_equal,
            x_int,  # return input bits as-is (NaN or self)
            tl.where(is_zero_cross, x_int + cross_const, x_int + normal_inc),
        )

        return result_int.to(input.dtype, bitcast=True)
    else:
        # float32
        return tl_extra_shim.nextafter(input, other)


def nextafter(input, other, *, out=None):
    logger.debug("GEMS NEXTAFTER")
    if out is not None:
        return nextafter_func(input, other, out0=out)
    return nextafter_func(input, other)


def nextafter_(input, other):
    logger.debug("GEMS NEXTAFTER_")
    return nextafter_func(input, other, out0=input)
