# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import numpy as np
import torch
import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


def _unwrap_if_constexpr(o):
    return o.value if isinstance(o, tl.constexpr) else o


@tl.constexpr
def _needs_upcast(num_bits):
    num_bits = _unwrap_if_constexpr(num_bits)
    return num_bits < 32


@tl.constexpr
def _get_sign_bit_mask(num_bits):
    num_bits = _unwrap_if_constexpr(num_bits)
    return 1 << (num_bits - 1)


@pointwise_dynamic(promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def nextafter_kernel(x, y):
    num_bits: tl.constexpr = x.dtype.primitive_bitwidth
    if _needs_upcast(num_bits):
        # For fp16/bf16: upcast to fp32 so int32 bitcast roundtrip works.
        # Triton CUDA does not support int16, so float→int16→float bitcast fails.
        x_f32 = x.to(tl.float32)
        y_f32 = y.to(tl.float32)
        is_nan = (x_f32 != x_f32) | (y_f32 != y_f32)
        x_int = x_f32.to(tl.int32, bitcast=True)
        sign_bit_mask: tl.constexpr = _get_sign_bit_mask(32)
        toward_pos_inf = y_f32 > x_f32
        is_neg = x_int < 0
        step = tl.where(is_neg ^ toward_pos_inf, 1, -1)
        result_int = x_int + step
        result_int = tl.where(
            (x_int == 0) & ~toward_pos_inf, -sign_bit_mask, result_int
        )
        result_int = tl.where((x_int == -sign_bit_mask) & toward_pos_inf, 1, result_int)
        result_f32 = result_int.to(tl.float32, bitcast=True)
        result = result_f32.to(x.dtype)
        result = tl.where(x_f32 == y_f32, y_f32, result)
        result = tl.where(is_nan, float("nan"), result)
    else:
        is_nan = (x != x) | (y != y)
        int_dtype = tl.core.get_int_dtype(num_bits, True)
        sign_bit_mask: tl.constexpr = _get_sign_bit_mask(num_bits)
        x_int = x.to(int_dtype, bitcast=True)
        toward_pos_inf = y > x
        is_neg = x_int < 0
        step = tl.where(is_neg ^ toward_pos_inf, 1, -1)
        result_int = x_int + step
        result_int = tl.where(
            (x_int == 0) & ~toward_pos_inf, -sign_bit_mask, result_int
        )
        result_int = tl.where((x_int == -sign_bit_mask) & toward_pos_inf, 1, result_int)
        result = result_int.to(x.dtype, bitcast=True)
        result = tl.where(x == y, y, result)
        result = tl.where(is_nan, float("nan"), result)

    return result


@pointwise_dynamic(is_tensor=[True, False], promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def nextafter_kernel_tensor_scalar(x, y):
    num_bits: tl.constexpr = x.dtype.primitive_bitwidth
    if _needs_upcast(num_bits):
        x_f32 = x.to(tl.float32)
        y_f32 = y.to(tl.float32)
        is_nan = (x_f32 != x_f32) | (y_f32 != y_f32)
        x_int = x_f32.to(tl.int32, bitcast=True)
        sign_bit_mask: tl.constexpr = _get_sign_bit_mask(32)
        toward_pos_inf = y_f32 > x_f32
        is_neg = x_int < 0
        step = tl.where(is_neg ^ toward_pos_inf, 1, -1)
        result_int = x_int + step
        result_int = tl.where(
            (x_int == 0) & ~toward_pos_inf, -sign_bit_mask, result_int
        )
        result_int = tl.where((x_int == -sign_bit_mask) & toward_pos_inf, 1, result_int)
        result_f32 = result_int.to(tl.float32, bitcast=True)
        result = result_f32.to(x.dtype)
        result = tl.where(x_f32 == y_f32, y_f32, result)
        result = tl.where(is_nan, float("nan"), result)
    else:
        is_nan = (x != x) | (y != y)
        int_dtype = tl.core.get_int_dtype(num_bits, True)
        sign_bit_mask: tl.constexpr = _get_sign_bit_mask(num_bits)
        x_int = x.to(int_dtype, bitcast=True)
        toward_pos_inf = y > x
        is_neg = x_int < 0
        step = tl.where(is_neg ^ toward_pos_inf, 1, -1)
        result_int = x_int + step
        result_int = tl.where(
            (x_int == 0) & ~toward_pos_inf, -sign_bit_mask, result_int
        )
        result_int = tl.where((x_int == -sign_bit_mask) & toward_pos_inf, 1, result_int)
        result = result_int.to(x.dtype, bitcast=True)
        result = tl.where(x == y, y, result)
        result = tl.where(is_nan, float("nan"), result)

    return result


@pointwise_dynamic(is_tensor=[False, True], promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def nextafter_kernel_scalar_tensor(x, y):
    num_bits: tl.constexpr = y.dtype.primitive_bitwidth
    if _needs_upcast(num_bits):
        x_f32 = x.to(tl.float32)
        y_f32 = y.to(tl.float32)
        is_nan = (x_f32 != x_f32) | (y_f32 != y_f32)
        x_int = x_f32.to(tl.int32, bitcast=True)
        sign_bit_mask: tl.constexpr = _get_sign_bit_mask(32)
        toward_pos_inf = y_f32 > x_f32
        is_neg = x_int < 0
        step = tl.where(is_neg ^ toward_pos_inf, 1, -1)
        result_int = x_int + step
        result_int = tl.where(
            (x_int == 0) & ~toward_pos_inf, -sign_bit_mask, result_int
        )
        result_int = tl.where((x_int == -sign_bit_mask) & toward_pos_inf, 1, result_int)
        result_f32 = result_int.to(tl.float32, bitcast=True)
        result = result_f32.to(y.dtype)
        result = tl.where(x_f32 == y_f32, y_f32, result)
        result = tl.where(is_nan, float("nan"), result)
    else:
        is_nan = (x != x) | (y != y)
        int_dtype = tl.core.get_int_dtype(num_bits, True)
        sign_bit_mask: tl.constexpr = _get_sign_bit_mask(num_bits)
        x_int = x.to(int_dtype, bitcast=True)
        toward_pos_inf = y > x
        is_neg = x_int < 0
        step = tl.where(is_neg ^ toward_pos_inf, 1, -1)
        result_int = x_int + step
        result_int = tl.where(
            (x_int == 0) & ~toward_pos_inf, -sign_bit_mask, result_int
        )
        result_int = tl.where((x_int == -sign_bit_mask) & toward_pos_inf, 1, result_int)
        result = result_int.to(y.dtype, bitcast=True)
        result = tl.where(x == y, y, result)
        result = tl.where(is_nan, float("nan"), result)

    return result


def nextafter_(A, B):
    logger.debug("GEMS NEXTAFTER_")
    if isinstance(A, torch.Tensor) and isinstance(B, torch.Tensor):
        return nextafter_kernel(A, B, out0=A)
    elif isinstance(A, torch.Tensor):
        return nextafter_kernel_tensor_scalar(A, B, out0=A)
    elif isinstance(B, torch.Tensor):
        return nextafter_kernel_scalar_tensor(A, B)
    else:
        # Both scalar
        return torch.tensor(np.nextafter(A, B))
