# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
import math

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as tle

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def _pdist_forward_p2_kernel(
    x_ptr,
    out_ptr,
    N,
    M,
    stride_x,
    stride_out,
    BLOCK_M: tl.constexpr,
):
    """Forward kernel for p=2 (Euclidean distance) case."""
    # Each program handles one pair of rows
    pid = tle.program_id(0)

    # Convert flat index to (i, j) pair where i < j
    # pdist output indices: for row i, pairs are (i, i+1), (i, i+2), ..., (i, n-1)
    # Total pairs before row i: i * N - (i * (i + 1)) // 2
    # Within row i's pairs: j - i - 1

    # Binary search to find row i for this output index
    # N*(N-1)//2 total pairs
    num_pairs = N * (N - 1) // 2

    if pid >= num_pairs:
        return

    # Find which row this pair belongs to
    # We need smallest i such that i * N - (i * (i + 1)) // 2 > pid
    # This is the cumulative count of pairs up to row i-1
    lo = 0
    hi = N - 1
    while lo < hi:
        mid = (lo + hi) // 2
        pairs_before_mid = mid * N - (mid * (mid + 1)) // 2
        if pairs_before_mid <= pid:
            lo = mid + 1
        else:
            hi = mid

    i = lo - 1 if lo > 0 else 0
    pairs_before_i = i * N - (i * (i + 1)) // 2
    j = pid - pairs_before_i + i + 1

    if i >= N or j >= N:
        return

    # Load row i and row j
    i_offset = i * stride_x
    j_offset = j * stride_x

    m_offsets = tl.arange(0, BLOCK_M)
    m_mask = m_offsets < M

    xi_vals = tl.load(x_ptr + i_offset + m_offsets, mask=m_mask, other=0.0).to(
        tl.float32
    )
    xj_vals = tl.load(x_ptr + j_offset + m_offsets, mask=m_mask, other=0.0).to(
        tl.float32
    )

    # Compute Euclidean distance: sum((xi - xj)^2)
    diff = xi_vals - xj_vals
    sq_dist = diff * diff
    dist = tl.sum(sq_dist, axis=0)
    dist = tl.sqrt(dist)

    out_idx = pid * stride_out
    tl.store(out_ptr + out_idx, dist.to(out_ptr.dtype.element_ty))


@libentry()
@triton.jit
def _pdist_forward_p1_kernel(
    x_ptr,
    out_ptr,
    N,
    M,
    stride_x,
    stride_out,
    BLOCK_M: tl.constexpr,
):
    """Forward kernel for p=1 (Manhattan distance) case."""
    pid = tle.program_id(0)

    num_pairs = N * (N - 1) // 2

    if pid >= num_pairs:
        return

    lo = 0
    hi = N - 1
    while lo < hi:
        mid = (lo + hi) // 2
        pairs_before_mid = mid * N - (mid * (mid + 1)) // 2
        if pairs_before_mid <= pid:
            lo = mid + 1
        else:
            hi = mid

    i = lo - 1 if lo > 0 else 0
    pairs_before_i = i * N - (i * (i + 1)) // 2
    j = pid - pairs_before_i + i + 1

    if i >= N or j >= N:
        return

    i_offset = i * stride_x
    j_offset = j * stride_x

    m_offsets = tl.arange(0, BLOCK_M)
    m_mask = m_offsets < M

    xi_vals = tl.load(x_ptr + i_offset + m_offsets, mask=m_mask, other=0.0).to(
        tl.float32
    )
    xj_vals = tl.load(x_ptr + j_offset + m_offsets, mask=m_mask, other=0.0).to(
        tl.float32
    )

    # Compute Manhattan distance: sum(|xi - xj|)
    diff = tl.abs(xi_vals - xj_vals)
    dist = tl.sum(diff, axis=0)

    out_idx = pid * stride_out
    tl.store(out_ptr + out_idx, dist.to(out_ptr.dtype.element_ty))


@libentry()
@triton.jit
def _pdist_forward_inf_kernel(
    x_ptr,
    out_ptr,
    N,
    M,
    stride_x,
    stride_out,
    BLOCK_M: tl.constexpr,
):
    """Forward kernel for p=inf (Chebyshev distance) case."""
    pid = tle.program_id(0)

    num_pairs = N * (N - 1) // 2

    if pid >= num_pairs:
        return

    lo = 0
    hi = N - 1
    while lo < hi:
        mid = (lo + hi) // 2
        pairs_before_mid = mid * N - (mid * (mid + 1)) // 2
        if pairs_before_mid <= pid:
            lo = mid + 1
        else:
            hi = mid

    i = lo - 1 if lo > 0 else 0
    pairs_before_i = i * N - (i * (i + 1)) // 2
    j = pid - pairs_before_i + i + 1

    if i >= N or j >= N:
        return

    i_offset = i * stride_x
    j_offset = j * stride_x

    m_offsets = tl.arange(0, BLOCK_M)
    m_mask = m_offsets < M

    xi_vals = tl.load(x_ptr + i_offset + m_offsets, mask=m_mask, other=0.0).to(
        tl.float32
    )
    xj_vals = tl.load(x_ptr + j_offset + m_offsets, mask=m_mask, other=0.0).to(
        tl.float32
    )

    # Compute Chebyshev distance: max(|xi - xj|)
    diff = tl.abs(xi_vals - xj_vals)
    dist = tl.max(diff, axis=0)

    out_idx = pid * stride_out
    tl.store(out_ptr + out_idx, dist.to(out_ptr.dtype.element_ty))


@libentry()
@triton.jit
def _pdist_forward_general_kernel(
    x_ptr,
    out_ptr,
    N,
    M,
    p_val,
    stride_x,
    stride_out,
    BLOCK_M: tl.constexpr,
):
    """Forward kernel for general p value."""
    pid = tle.program_id(0)

    num_pairs = N * (N - 1) // 2

    if pid >= num_pairs:
        return

    lo = 0
    hi = N - 1
    while lo < hi:
        mid = (lo + hi) // 2
        pairs_before_mid = mid * N - (mid * (mid + 1)) // 2
        if pairs_before_mid <= pid:
            lo = mid + 1
        else:
            hi = mid

    i = lo - 1 if lo > 0 else 0
    pairs_before_i = i * N - (i * (i + 1)) // 2
    j = pid - pairs_before_i + i + 1

    if i >= N or j >= N:
        return

    i_offset = i * stride_x
    j_offset = j * stride_x

    m_offsets = tl.arange(0, BLOCK_M)
    m_mask = m_offsets < M

    xi_vals = tl.load(x_ptr + i_offset + m_offsets, mask=m_mask, other=0.0).to(
        tl.float32
    )
    xj_vals = tl.load(x_ptr + j_offset + m_offsets, mask=m_mask, other=0.0).to(
        tl.float32
    )

    # Compute p-norm distance
    diff = tl.abs(xi_vals - xj_vals)

    # For p=0 (Hamming-like), count non-zero elements
    if p_val == 0.0:
        dist = tl.sum(tl.where(diff != 0.0, 1.0, 0.0), axis=0)
    else:
        # General case: (sum(|diff|^p))^(1/p)
        powered = tl.where(diff > 0.0, tl.exp(p_val * tl.log(diff)), 0.0)
        sum_powered = tl.sum(powered, axis=0)
        dist = tl.where(sum_powered > 0.0, tl.exp(tl.log(sum_powered) / p_val), 0.0)

    out_idx = pid * stride_out
    tl.store(out_ptr + out_idx, dist.to(out_ptr.dtype.element_ty))


def pdist(x, p=2.0):
    """Compute p-norm distance between every pair of row vectors in the input.

    Args:
        x: Input tensor of shape (N, M)
        p: p value for the p-norm distance to calculate

    Returns:
        Tensor of shape (N*(N-1)//2,) containing pairwise distances
    """
    logger.debug("GEMS PDIST")

    assert x.ndim == 2, "pdist only supports 2D input"
    if x.dtype != torch.float32:
        raise RuntimeError(
            f"pdist Triton kernel supports torch.float32, but got {x.dtype}"
        )
    N = x.shape[0]
    M = x.shape[1]

    if N < 2:
        raise ValueError("pdist requires at least 2 rows")

    x = x.contiguous()
    num_pairs = N * (N - 1) // 2
    out = torch.empty(num_pairs, dtype=x.dtype, device=x.device)

    BLOCK_M = min(triton.next_power_of_2(M), 1024)

    with torch_device_fn.device(x.device):
        if p == 2.0:
            _pdist_forward_p2_kernel[(num_pairs,)](
                x,
                out,
                N,
                M,
                x.stride(0),
                out.stride(0),
                BLOCK_M=BLOCK_M,
            )
        elif p == 1.0:
            _pdist_forward_p1_kernel[(num_pairs,)](
                x,
                out,
                N,
                M,
                x.stride(0),
                out.stride(0),
                BLOCK_M=BLOCK_M,
            )
        elif math.isinf(p):
            _pdist_forward_inf_kernel[(num_pairs,)](
                x,
                out,
                N,
                M,
                x.stride(0),
                out.stride(0),
                BLOCK_M=BLOCK_M,
            )
        else:
            _pdist_forward_general_kernel[(num_pairs,)](
                x,
                out,
                N,
                M,
                p,
                x.stride(0),
                out.stride(0),
                BLOCK_M=BLOCK_M,
            )

    return out
