# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
import math

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit
def reflection_pad1d_backward_kernel(
    grad_output_ptr,
    grad_input_ptr,
    B,
    W_in,
    pad_left,
    W_out,
    BLOCK_W: tl.constexpr,
):
    pid_b = tl.program_id(axis=0)
    pid_w = tl.program_id(axis=1)

    offs_w = pid_w * BLOCK_W + tl.arange(0, BLOCK_W)
    mask_out = offs_w < W_out

    base_out = pid_b * W_out
    base_in = pid_b * W_in

    grad = tl.load(grad_output_ptr + base_out + offs_w, mask=mask_out, other=0.0)

    x_off = offs_w.to(tl.int32) - pad_left
    Wm1 = W_in - 1
    twin = 2 * max(Wm1, 1)
    x_abs = tl.abs(x_off)
    m = x_abs % twin
    iw = tl.where(m < W_in, m, twin - m)

    tl.atomic_add(grad_input_ptr + base_in + iw, grad, mask=mask_out)


def _launch_reflection_pad1d_backward(
    grad_output: torch.Tensor,
    input: torch.Tensor,
    padding,
):
    if not isinstance(padding, (list, tuple)) or len(padding) != 2:
        raise ValueError(
            "padding must be a sequence of length 2: (pad_left, pad_right)"
        )
    pad_left, pad_right = int(padding[0]), int(padding[1])
    if pad_left < 0 or pad_right < 0:
        raise ValueError("padding values must be >= 0")
    if input.dim() < 1:
        raise ValueError("input must have at least 1 dimension")

    grad_output = grad_output.contiguous()
    x = input.contiguous()

    W_in = int(x.shape[-1])
    if W_in <= 0:
        raise ValueError("last dimension (width) must be > 0")

    W_out = W_in + pad_left + pad_right
    leading_shape = x.shape[:-1]
    B = int(math.prod(leading_shape)) if len(leading_shape) > 0 else 1

    if pad_left == 0 and pad_right == 0:
        return grad_output[:, :].contiguous().clone()

    if W_in < 2:
        raise ValueError(
            "input width must be at least 2 for reflection padding when padding > 0"
        )
    if pad_left >= W_in or pad_right >= W_in:
        raise ValueError(
            "padding values must be less than the input width for reflection padding"
        )

    grad_input = torch.zeros_like(x)

    BLOCK_W = triton.next_power_of_2(W_out)
    grid = (B, triton.cdiv(W_out, BLOCK_W))
    with torch_device_fn.device(x.device):
        reflection_pad1d_backward_kernel[grid](
            grad_output, grad_input, B, W_in, pad_left, W_out, BLOCK_W=BLOCK_W
        )
    return grad_input


def reflection_pad1d_backward(grad_output: torch.Tensor, input: torch.Tensor, padding):
    logger.debug("GEMS REFLECTION_PAD1D_BACKWARD")
    return _launch_reflection_pad1d_backward(grad_output, input, padding)
