# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit
def _resize_kernel(src_ptr, dst_ptr, n_elements, BLOCK_SIZE: tl.constexpr):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements
    # Load from source
    vals = tl.load(src_ptr + offsets, mask=mask)
    # Store to destination
    tl.store(dst_ptr + offsets, vals, mask=mask)


def resize(inp: torch.Tensor, size, memory_format=None):
    logger.debug("GEMS RESIZE")

    # Convert size to tuple if it's not already
    if not isinstance(size, tuple):
        size = tuple(size)

    # Calculate total number of elements
    total_elements = 1
    for dim in size:
        total_elements *= dim

    # Create output tensor with new shape
    out = torch.empty(size, device=inp.device, dtype=inp.dtype)

    # If input is empty or output is empty, return empty tensor
    if inp.numel() == 0 or out.numel() == 0:
        return out

    n_elements = out.numel()
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    with torch_device_fn.device(inp.device):
        _resize_kernel[grid](inp, out, n_elements, BLOCK_SIZE=1024)

    return out


def resize_(inp: torch.Tensor, size, memory_format=None):
    logger.debug("GEMS RESIZE_")

    if not isinstance(size, tuple):
        size = tuple(size)

    inp.set_(inp.untyped_storage(), 0, size)
    return inp
