# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems import runtime
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)

# Fixed inner block size for mat-vec product loops (compile-time literal).
_CHUNK = 64


@libentry()
@triton.autotune(
    configs=runtime.get_tuned_config("rnn_relu"),
    key=["seq_len", "input_size", "hidden_size"],
)
@triton.jit
def rnn_relu_forward_kernel(
    input_ptr,
    hx_ptr,
    weight_ih_ptr,
    weight_hh_ptr,
    bias_ih_ptr,
    bias_hh_ptr,
    output_ptr,
    hidden_output_ptr,
    hidden_read_ptr,
    seq_len,
    batch_size,
    input_size,
    hidden_size,
    batch_first: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    """
    Triton kernel for single-layer unidirectional RNN with ReLU activation.

    Grid: (batch_size,) — one program per batch element.
    Each program computes all time steps sequentially.

    Double-buffered hidden state: hidden_read_ptr holds the previous-step
    hidden state (read-only within a time step) while hidden_output_ptr
    accumulates the current-step hidden state.  This avoids chunk-level
    race conditions when hidden_size > BLOCK_SIZE.
    """
    batch_idx = tl.program_id(0)
    if batch_idx >= batch_size:
        return

    CHUNK: tl.constexpr = 64  # inner block for mat-vec loops
    num_hid_blocks = tl.cdiv(hidden_size, BLOCK_SIZE)
    chunk_offs = tl.arange(0, CHUNK)
    bid_offs = tl.arange(0, BLOCK_SIZE)

    # --- initialize hidden state in global scratch ---
    _init_hidden(
        hidden_output_ptr,
        hx_ptr,
        batch_idx,
        hidden_size,
        num_hid_blocks,
        BLOCK_SIZE,
    )

    # Stride helpers.
    if batch_first:
        batch_inp_stride = seq_len * input_size
        batch_out_stride = seq_len * hidden_size
    else:
        batch_inp_stride = input_size
        batch_out_stride = hidden_size

    h_scratch_base = hidden_output_ptr + batch_idx * hidden_size
    h_read_base = hidden_read_ptr + batch_idx * hidden_size

    for t in range(seq_len):
        if batch_first:
            t_inp_off = batch_idx * batch_inp_stride + t * input_size
            t_out_off = batch_idx * batch_out_stride + t * hidden_size
        else:
            t_inp_off = t * (batch_size * input_size) + batch_idx * input_size
            t_out_off = t * (batch_size * hidden_size) + batch_idx * hidden_size

        # Double-buffer: snapshot previous-step hidden state into read buffer
        # so later chunks don't read already-updated values from this step.
        for hid_block in range(num_hid_blocks):
            h_start = hid_block * BLOCK_SIZE
            h_offs = h_start + bid_offs
            h_mask = h_offs < hidden_size
            h_val = tl.load(h_scratch_base + h_offs, mask=h_mask, other=0.0)
            tl.store(h_read_base + h_offs, h_val, mask=h_mask)

        # Process hidden_size in BLOCK_SIZE-sized output chunks.
        for hid_block in range(num_hid_blocks):
            h_start = hid_block * BLOCK_SIZE
            h_offs = h_start + bid_offs
            h_mask = h_offs < hidden_size

            # --- ih = W_ih[h_offs, :] @ x_t + b_ih ---
            ih_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)

            for inp_start in range(0, input_size, CHUNK):
                i_offs = inp_start + chunk_offs
                i_mask = i_offs < input_size

                # W_ih tile: (BLOCK_SIZE, CHUNK) — row-major.
                w_offs = h_offs[:, None] * input_size + i_offs[None, :]
                w_mask = h_mask[:, None] & i_mask[None, :]
                w_tile = tl.load(weight_ih_ptr + w_offs, mask=w_mask, other=0.0).to(
                    tl.float32
                )

                x_tile = tl.load(
                    input_ptr + t_inp_off + i_offs, mask=i_mask, other=0.0
                ).to(tl.float32)

                ih_acc += tl.sum(w_tile * x_tile[None, :], axis=1)

            if bias_ih_ptr is not None:
                b_ih = tl.load(bias_ih_ptr + h_offs, mask=h_mask, other=0.0).to(
                    tl.float32
                )
                ih_acc += b_ih

            # --- hh = W_hh[h_offs, :] @ h_prev + b_hh ---
            hh_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)

            for hid_in_start in range(0, hidden_size, CHUNK):
                j_offs = hid_in_start + chunk_offs
                j_mask = j_offs < hidden_size

                # W_hh tile: (BLOCK_SIZE, CHUNK) — row-major.
                w_offs = h_offs[:, None] * hidden_size + j_offs[None, :]
                w_mask = h_mask[:, None] & j_mask[None, :]
                w_tile = tl.load(weight_hh_ptr + w_offs, mask=w_mask, other=0.0).to(
                    tl.float32
                )

                h_tile = tl.load(h_read_base + j_offs, mask=j_mask, other=0.0).to(
                    tl.float32
                )

                hh_acc += tl.sum(w_tile * h_tile[None, :], axis=1)

            if bias_hh_ptr is not None:
                b_hh = tl.load(bias_hh_ptr + h_offs, mask=h_mask, other=0.0).to(
                    tl.float32
                )
                hh_acc += b_hh

            # --- h_new = relu(ih + hh) ---
            h_new = ih_acc + hh_acc
            h_new = tl.where(h_new > 0, h_new, 0.0)

            # Write to output (all time steps) and to scratch (next step).
            tl.store(output_ptr + t_out_off + h_offs, h_new, mask=h_mask)
            tl.store(h_scratch_base + h_offs, h_new, mask=h_mask)

    # Final hidden state resides at h_scratch_base → hidden_output_ptr.


@triton.jit
def _init_hidden(
    hidden_output_ptr,
    hx_ptr,
    batch_idx,
    hidden_size,
    num_hid_blocks,
    BLOCK_SIZE: tl.constexpr,
):
    """Initialize the scratch hidden state from hx (or zeros)."""
    bid_offs = tl.arange(0, BLOCK_SIZE)
    for hid_block in range(num_hid_blocks):
        h_start = hid_block * BLOCK_SIZE
        h_offs = h_start + bid_offs
        h_mask = h_offs < hidden_size
        if hx_ptr is not None:
            h_val = tl.load(
                hx_ptr + batch_idx * hidden_size + h_offs,
                mask=h_mask,
                other=0.0,
            ).to(tl.float32)
        else:
            h_val = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
        tl.store(
            hidden_output_ptr + batch_idx * hidden_size + h_offs,
            h_val,
            mask=h_mask,
        )


# ---------------------------------------------------------------------------
# Host-side helpers
# ---------------------------------------------------------------------------


def _params_unpack(params, has_biases):
    """Unpack RNN _flat_weights in correct PyTorch order.

    PyTorch _flat_weights: [w_ih, w_hh, b_ih, b_hh]
    (The original KernelGen-generated code incorrectly swapped b_ih and w_hh.)
    """
    if has_biases:
        weight_ih, weight_hh, bias_ih, bias_hh = params[:4]
        return weight_ih, weight_hh, bias_ih, bias_hh
    else:
        return params[0], params[1], None, None


def rnn_relu_kernel_forward(
    input,
    hx,
    params,
    has_biases,
    num_layers,
    dropout,
    train,
    bidirectional,
    batch_first,
):
    """Launch the Triton RNN ReLU kernel after validating config."""
    logger.debug("GEMS RNN_RELU FORWARD KERNEL LAUNCH")

    if num_layers > 1 or bidirectional:
        raise NotImplementedError(
            "GEMS RNN_RELU only supports single-layer unidirectional"
        )
    if dropout > 0 and train:
        raise NotImplementedError(
            "GEMS RNN_RELU does not support dropout in train mode"
        )

    if batch_first:
        batch_size, seq_len, input_size = input.shape
    else:
        seq_len, batch_size, input_size = input.shape

    if hx is not None:
        hidden_size = hx.shape[2]
    elif len(params) > 0:
        hidden_size = params[0].shape[0]
    else:
        raise ValueError("Cannot determine hidden_size")

    num_directions = 2 if bidirectional else 1
    if batch_first:
        output_shape = (batch_size, seq_len, hidden_size * num_directions)
    else:
        output_shape = (seq_len, batch_size, hidden_size * num_directions)

    output = torch.empty(output_shape, dtype=input.dtype, device=input.device)
    hidden_shape = (num_layers * num_directions, batch_size, hidden_size)
    hidden = torch.empty(hidden_shape, dtype=input.dtype, device=input.device)
    hidden_read = torch.empty(hidden_shape, dtype=input.dtype, device=input.device)

    if hx is None:
        hx = torch.zeros(hidden_shape, dtype=input.dtype, device=input.device)

    weight_ih, weight_hh, bias_ih, bias_hh = _params_unpack(params, has_biases)

    input = input.contiguous()
    output = output.contiguous()
    hidden = hidden.contiguous()
    hidden_read = hidden_read.contiguous()
    weight_ih = weight_ih.contiguous()
    weight_hh = weight_hh.contiguous()
    if bias_ih is not None:
        bias_ih = bias_ih.contiguous()
    if bias_hh is not None:
        bias_hh = bias_hh.contiguous()

    grid = (batch_size,)

    with runtime.torch_device_fn.device(input.device):
        rnn_relu_forward_kernel[grid](
            input,
            hx,
            weight_ih,
            weight_hh,
            bias_ih,
            bias_hh,
            output,
            hidden,
            hidden_read,
            seq_len,
            batch_size,
            input_size,
            hidden_size,
            batch_first,
        )

    return output, hidden


class RnnReluFunction(torch.autograd.Function):
    """Autograd for single-layer unidirectional RNN with ReLU.

    Forward  → Triton kernel (fast).
    Backward → recompute forward in native PyTorch, then autograd.
               The Triton kernel is opaque to PyTorch autograd, so the
               backward pass reconstructs the computation graph using
               native PyTorch operations.
    """

    @staticmethod
    def forward(
        ctx,
        input,
        hx,
        params,
        has_biases,
        num_layers,
        dropout,
        train,
        bidirectional,
        batch_first,
    ):
        logger.debug("GEMS RNN_RELU FUNCTION FORWARD")

        if num_layers > 1 or bidirectional or (dropout > 0 and train):
            raise NotImplementedError(
                "GEMS RNN_RELU only supports single-layer unidirectional"
            )

        ctx.save_for_backward(input, hx)
        ctx.params = params
        ctx.has_biases = has_biases
        ctx.num_layers = num_layers
        ctx.bidirectional = bidirectional
        ctx.batch_first = batch_first

        return rnn_relu_kernel_forward(
            input,
            hx,
            params,
            has_biases,
            num_layers,
            dropout,
            train,
            bidirectional,
            batch_first,
        )

    @staticmethod
    def backward(ctx, grad_output, grad_hidden):
        logger.debug("GEMS RNN_RELU FUNCTION BACKWARD")

        input, hx = ctx.saved_tensors
        params = ctx.params
        has_biases = ctx.has_biases
        num_layers = ctx.num_layers
        bidirectional = ctx.bidirectional
        batch_first = ctx.batch_first

        if num_layers > 1 or bidirectional:
            raise NotImplementedError(
                "GEMS RNN_RELU backward: unsupported configuration"
            )

        weight_ih, weight_hh, bias_ih, bias_hh = _params_unpack(params, has_biases)

        if batch_first:
            batch_size, seq_len, input_size = input.shape
        else:
            seq_len, batch_size, input_size = input.shape

        with torch.enable_grad():
            # ---- recompute forward in native PyTorch ----
            h = hx[0].clone()  # (batch, hidden)
            outputs = []
            for t_idx in range(seq_len):
                if batch_first:
                    xt = input[:, t_idx, :]
                else:
                    xt = input[t_idx, :, :]
                # h = relu(xt @ W_ih^T + h @ W_hh^T + b_ih + b_hh)
                pre_act = (
                    torch.addmm(bias_ih, xt, weight_ih.t())
                    if has_biases
                    else torch.mm(xt, weight_ih.t())
                )
                pre_act += (
                    torch.addmm(bias_hh, h, weight_hh.t())
                    if has_biases
                    else torch.mm(h, weight_hh.t())
                )
                h = torch.relu(pre_act)
                outputs.append(h)

            if batch_first:
                output_native = torch.stack(outputs, dim=1)
            else:
                output_native = torch.stack(outputs, dim=0)
            hx_native = h.unsqueeze(0)

            # ---- compute gradients via autograd ----
            grad_output_flat = grad_output.reshape(output_native.shape)
            grad_hidden_flat = grad_hidden.reshape(hx_native.shape)

            all_weight_grads = torch.autograd.grad(
                outputs=[output_native, hx_native],
                inputs=[input, hx] + list(params),
                grad_outputs=[grad_output_flat, grad_hidden_flat],
                retain_graph=False,
            )

        grad_input = all_weight_grads[0]
        grad_hx = all_weight_grads[1]
        grad_params = all_weight_grads[2:]

        for p, g in zip(params, grad_params):
            if g is not None:
                if p.grad is None:
                    p.grad = g.to(p.dtype)
                else:
                    p.grad.add_(g)

        return (
            grad_input,
            grad_hx,
            None,  # params — not a Variable, grads accumulated manually above
            None,  # has_biases
            None,  # num_layers
            None,  # dropout
            None,  # train
            None,  # bidirectional
            None,  # batch_first
        )


def rnn_relu(
    input,
    hx=None,
    params=None,
    has_biases=True,
    num_layers=1,
    dropout=0.0,
    train=False,
    bidirectional=False,
    batch_first=False,
):
    """Applies an Elman RNN with ReLU activation.

    Uses Triton kernel for forward, native PyTorch recomputation for backward.
    Supports single-layer, unidirectional RNN without dropout.
    Multi-layer, bidirectional, and train-mode dropout raise NotImplementedError.
    """
    logger.debug("GEMS RNN_RELU")

    if params is None:
        raise ValueError("params must be provided")
    if hx is None:
        raise ValueError("hx must be provided to match torch.rnn_relu schema")

    if num_layers == 1 and not bidirectional and dropout == 0:
        return RnnReluFunction.apply(
            input,
            hx,
            params,
            has_biases,
            num_layers,
            dropout,
            train,
            bidirectional,
            batch_first,
        )
    else:
        raise NotImplementedError(
            "GEMS RNN_RELU only supports single-layer unidirectional without dropout"
        )
