# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

from flag_gems.ops.digamma_ import digamma

logger = logging.getLogger(__name__)


def special_digamma(A):
    """Computes the digamma function (alias for torch.special.digamma)."""
    logger.debug("GEMS SPECIAL_DIGAMMA")
    return digamma(A)
