# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, "DEFAULT")])
@triton.jit
def special_digamma_kernel(x):
    x_f32 = x.to(tl.float32)

    pi = 3.1415926535897932384626433832795028841971

    # Reflection for x < 0.5: psi(x) = psi(1 - x) - pi * cot(pi * x)
    reflect_mask = x_f32 < 0.5
    xr = tl.where(reflect_mask, 1.0 - x_f32, x_f32)

    # Use recurrence to shift xr to >= 8 for better asymptotic precision
    s = tl.zeros_like(x_f32)
    y = xr
    for _ in range(8):
        m = y < 8.0
        s = s - tl.where(m, 1.0 / y, 0.0)
        y = tl.where(m, y + 1.0, y)

    # Asymptotic expansion for digamma at large y
    r = 1.0 / y
    r2 = r * r
    t2 = r2
    t4 = t2 * t2
    t6 = t4 * t2
    t8 = t4 * t4
    series = (
        (-0.5 * r)
        + (-1.0 / 12.0) * t2
        + (1.0 / 120.0) * t4
        + (-1.0 / 252.0) * t6
        + (1.0 / 240.0) * t8
    )
    psi_y = tl.log(y) + s + series

    # Apply reflection if needed
    cot_term = tl.cos(pi * x_f32) / tl.sin(pi * x_f32)
    result = tl.where(reflect_mask, psi_y - pi * cot_term, psi_y)

    return result.to(x.dtype)


def special_digamma(A):
    logger.debug("GEMS SPECIAL_DIGAMMA")
    return special_digamma_kernel(A)
