# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
# Generated by FlagGems: https://github.com/flag-os/FlagGems
"""
Implementation of Airy Ai function.
Uses Taylor series for small values and asymptotic approximation for large values.
"""
import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, "DEFAULT")])
@triton.jit
def special_airy_ai_func(x):
    xf = x.to(tl.float32)
    x_abs = tl.abs(xf)
    x_sign = tl.where(xf >= 0.0, 1.0, -1.0)

    # Constants
    SQRTPI_INV = 0.564189583547756
    TWO_THIRDS = 0.6666666666666666
    PI = 3.141592653589793

    # Small region: |x| <= 1.0
    is_small = x_abs <= 1.0

    # Taylor series coefficients
    c0 = 0.355028053887535
    c1 = -0.258102603742147
    c2 = -0.014791633174910
    c3 = 0.104316751884424
    c4 = -0.016807637872873
    c5 = -0.001393772920686
    c6 = 0.000167045880663
    c7 = 0.000036694336230

    small = (
        c0
        + xf * (c1 + xf * (c2 + xf * (c3 + xf * (c4 + xf * (c5 + xf * (c6 + xf * c7))))))
    )

    # Large region: |x| > 1.0
    sqrt_abs = tl.sqrt(x_abs)
    z = TWO_THIRDS * x_abs * sqrt_abs
    inv_x = 1.0 / x_abs

    # Rational function approximation
    p0 = 1.0
    p1 = -0.416462787153520
    p2 = -0.077176480130308

    q0 = 1.0
    q1 = 0.342360170672950
    q2 = 0.107795141266403

    p_val = p0 + inv_x * (p1 + inv_x * p2)
    q_val = q0 + inv_x * (q1 + inv_x * q2)
    rational = p_val / q_val

    # Amplitude
    amp = SQRTPI_INV / (sqrt_abs * tl.sqrt(sqrt_abs))

    # Positive x: decaying
    exp_arg = -TWO_THIRDS * xf * sqrt_abs
    pos = rational * tl.exp(exp_arg)

    # Negative x: oscillation
    phase = z - PI / 4.0
    neg = amp * rational * tl.cos(phase)

    large = tl.where(x_sign > 0.0, pos, neg)

    result = tl.where(is_small, small, large)

    return result.to(x.dtype)


def special_airy_ai(A):
    logger.debug("GEMS SPECIAL_AIRY_AI")
    return special_airy_ai_func(A)


def special_airy_ai_out(A, *, out=None):
    logger.debug("GEMS SPECIAL_AIRY_AI_OUT")
    if out is None:
        return special_airy_ai_func(A)
    special_airy_ai_func(A, out0=out)
    return out