# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def xlog1py_func(x, y):
    # xlog1py(x, y) = x * log1p(y) = x * log(1 + y)
    # Special cases:
    # - If y is NaN, result is NaN
    # - If x is 0 and y is not NaN, result is 0
    # - Otherwise: x * log(1 + y)
    x_f32 = x.to(tl.float32)
    y_f32 = y.to(tl.float32)

    # Check if y is NaN
    y_is_nan = y_f32 != y_f32

    # Check if x is zero
    x_is_zero = x_f32 == 0.0

    # log1p(y) = log(1 + y), but need to handle y = -1 (log(0) = -inf)
    # and y < -1 (log of negative number = nan)
    log1p_y = tl.log(1.0 + y_f32)

    # Result: x * log1p(y), but if x is 0 and y is not NaN, result is 0
    # This avoids 0 * inf = nan or 0 * -inf = nan
    result = tl.where(x_is_zero & ~y_is_nan, 0.0, x_f32 * log1p_y)
    return result.to(x.dtype)


def special_xlog1py(A, B):
    logger.debug("GEMS SPECIAL_XLOG1PY")
    return xlog1py_func(A, B)
