# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, "INT_TO_FLOAT")])
@triton.jit
def special_log1p_func(x):
    return tl.log(1.0 + x.to(tl.float32)).to(x.dtype)


def special_log1p(A):
    logger.debug("GEMS SPECIAL_LOG1P")
    if isinstance(A, torch.Tensor):
        return special_log1p_func(A)
    else:
        return torch.log(torch.tensor(A + 1.0))


def special_log1p_out(A, out):
    logger.debug("GEMS SPECIAL_LOG1P_OUT")
    return special_log1p_func(A, out0=out)
