# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

logger = logging.getLogger(__name__)


def transpose(self: torch.Tensor, dim0: int, dim1: int) -> torch.Tensor:
    """Return a view of the tensor with the two specified dimensions swapped.

    This is a zero-copy view operation that swaps the sizes and strides of
    ``dim0`` and ``dim1`` via :func:`torch.as_strided`, matching the semantics
    of ``aten::transpose.int`` (``Tensor(a) -> Tensor(a)``).
    """
    logger.debug("GEMS TRANSPOSE")

    ndim = self.dim()

    # Normalize negative dims using the same convention as aten.
    if dim0 < 0:
        dim0 += ndim
    if dim1 < 0:
        dim1 += ndim

    # Match aten's IndexError message for out-of-range dimensions.
    if not (0 <= dim0 < ndim):
        raise IndexError(
            f"Dimension out of range (expected to be in range of "
            f"[-{ndim}, {ndim - 1}], but got {dim0 - ndim if dim0 < 0 else dim0})"
        )
    if not (0 <= dim1 < ndim):
        raise IndexError(
            f"Dimension out of range (expected to be in range of "
            f"[-{ndim}, {ndim - 1}], but got {dim1 - ndim if dim1 < 0 else dim1})"
        )

    # 0D / 1D: no observable effect (swapping the only dimension with itself
    # is a no-op). Return a fresh view so the dispatcher sees a new tensor
    # (returning ``self`` directly is rejected by PyTorch's view-op checks).
    if ndim <= 1 or dim0 == dim1:
        return self.view(self.shape)

    shape = list(self.shape)
    strides = list(self.stride())
    shape[dim0], shape[dim1] = shape[dim1], shape[dim0]
    strides[dim0], strides[dim1] = strides[dim1], strides[dim0]
    return torch.as_strided(self, shape, strides)
