# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
from typing import Tuple

import torch

logger = logging.getLogger(__name__)


def unbind(input: torch.Tensor, dim: int = 0) -> Tuple[torch.Tensor, ...]:
    """Remove a tensor dimension.

    Returns a tuple of all slices along ``dim``, with that dimension removed.
    `torch.unbind` is a view operation: every returned slice shares storage with
    the input. We therefore build each slice as a zero-copy view via
    `torch.as_strided` (dropping ``dim`` from the size/stride and advancing the
    storage offset per slice) rather than copying data with a kernel.

    Args:
        input: The tensor to unbind
        dim: The dimension to remove

    Returns:
        A tuple of tensors, each a view into ``input``.
    """
    logger.debug("GEMS UNBIND")

    if dim < 0:
        dim = dim + input.ndim

    if dim < 0 or dim >= input.ndim:
        raise IndexError(
            f"Dimension out of range (expected to be in range of "
            f"[{-input.ndim}, {input.ndim - 1}], but got {dim})"
        )

    num_slices = input.shape[dim]

    # Shape/stride of each slice: the unbind dimension is removed.
    size = list(input.shape)
    del size[dim]
    stride = list(input.stride())
    step = stride.pop(dim)

    base_offset = input.storage_offset()
    return tuple(
        torch.as_strided(input, size, stride, base_offset + i * step)
        for i in range(num_slices)
    )
